.section .text
    .equ QEMU_URAT_ADDR, 0x09000000

    ldr r0, = 'H';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 'e';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 'l';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 'l';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 'o';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = ',';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 'T';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 'h';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 'i';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 's';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = ' ';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 'i';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 's';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = ' ';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 'B';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 'i';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 's';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 'o';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 'n';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 'O';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

    ldr r0, = 'S';
    ldr r1, = QEMU_URAT_ADDR;
    strb r0, [r1];

